### ISSUE TITLE
相同的代码，在Mac执行hugo生成html正常，Linux执行报错。

### ISSUE THREAD

**Issue by wlizhi** [hugo-fixit/shortcode-mmt-netease#2]
[root@iZuf6ba66869f3focrzwq3Z blog-code]# hugo
Start building sites … 
hugo v0.127.0-74e0f3bd63c51f3c7a0f07a7c779eec9e922957e+extended linux/amd64 BuildDate=2024-06-05T10:27:59Z VendorInfo=gohugoio

Total in 166 ms
Error: error building site: process: readAndProcessContent: "/blog/blog-code/content/message-board.md:13:1": failed to extract shortcode: template for shortcode "mmt-netease" not found

**Comment by Lruihao** [comment]
确保子模块拉去正常。
